# Generated by Django 2.0.1 on 2018-02-23 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='add_date',
        ),
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
